vyos:
  hosts:
    10.0.17.200:
      mac: 00:50:56:ba:41:8d
      hostname: blue1-fw
      wan_ip: 10.0.17.200
      lan_ip: 10.0.5.2
      lan: 10.0.5.0/24
      name_server: 10.0.17.4
      gateway: 10.0.17.2
      dhcp_name_server: 10.0.5.5
      shared_network: BLUE1
      dhcp_domain: blue1.local

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: network_cli
    ansible_network_os: vyos
    ansible_user: vyos
