linux:
  hosts:
  children:
    rocky:
      hosts:
        10.0.5.75:
          hostname: rocky-1
          lan_ip: 10.0.5.10
        10.0.5.76:
          hostname: rocky-2
          lan_ip: 10.0.5.11
        10.0.5.77:
          hostname: rocky-3
          lan_ip: 10.0.5.12
      vars:
        device: ens33
    ubuntu:
      hosts:
        10.0.5.80:
          hostname: ubuntu-1
          lan_ip: 10.0.5.30
        10.0.5.79:
          hostname: ubuntu-2
          lan_ip: 10.0.5.31
      vars:
        device: ens33

  vars:
    ansible_user: reed
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCXz/cxx5KH6HkCCQf90vudQ2SCYxSyVdPgLyk3O2WMzMREIa/f7rcVZScasiM7EJ7sT/9Ceef4OxNf+9iphW0EQDEXsASkuMdMjjNiGXRE9MR68GphW+Zm+DwZYF1bIStqcdUEMxMwYySJfjM4su+tsoHDTCr+oiL4LdS7FnuQ+sdmzIQwwjr7825KVsLHUOcEXQ8nUinIe7hnMC9zFp73+DisUATB6bYn6c0ugtz4sLFsoAbk7QrMg4iOl378LmY+kvzgEzu90uNK23e6KGzxROU0DSwrizalMjlNOiuOayh/qyYOwCrlCZ7CuHcWsA6rbEagFyCuOPhPFd7KTqSiZPWePShW11bR7WvX07M7XyvFYDtrMGb+s8+86pChW4ftHx4xOQkCWLBprRo0YhraMzyPRAiFXmhMgpA7Z/5Ai8ODeJ57CfIfaSNTTVGtov5CaZoycFHAHumf15piry0n6VI6QhK6g0AYXrozUvHIjCX5E8dTYUSNNcTJq7GP7wU= reed@xubuntu-wan"
    prefix: 24
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue1.local
