---
- name: blue1 vyos network configuration
  hosts: vyos
  tasks:
  - name: Retrieve VyOS version
    vyos.vyos.vyos_command:
      commands: show version
    register: version

  - name: Display VyOS version
    ansible.builtin.debug:
      var: version.stdout_lines

  - name: Configure VyOS DHCP
    vyos.vyos.vyos_config:
      save: true
      lines:
      - set service dhcp-server global-parameters 'local-address {{ lan_ip }};'
      - set service dhcp-server shared-network-name {{ shared_network }} authoritative
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan }} default-router '{{ lan_ip }}'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan }} name-server '{{ dhcp_name_server }}'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan }} domain-name '{{ dhcp_domain }}'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan }} lease '86400'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan }} range {{ shared_network }}-POOL start '10.0.5.75'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan }} range {{ shared_network }}-POOL stop '10.0.5.125'
